### ISSUE TITLE
undefined null is not an object (evaluating 'ReactNativeGetLocation.getCurrentPosition')

### ISSUE THREAD

**Issue by minh-dai** [douglasjunior/react-native-get-location#8] opened 2020-02-14 08:30 UTC
"react": "16.9.0",
"react-native": "0.61.5",

**Comment by douglasjunior** [comment] 2020-02-14 11:30
Probably you did not link the native project correctly. Without more information it is difficult to help.

**Comment by minh-dai** [comment] 2020-02-17 02:59
i using automatically link, but it not woking @@

**Comment by douglasjunior** [comment] 2020-02-17 11:26
In auto-linkin you dont need to do anything else, if its not working you have some problem with your project setup.

Please, take a look at the Sample project https://github.com/douglasjunior/react-native-get-location/tree/master/Sample

**Comment by gunnx** [comment] 2020-03-28 15:52
I just tried to install and also only get null back. Im using emulator and setting location in there

**Comment by douglasjunior** [comment] 2020-03-28 17:45
I will close this issue because the information here does not help us to identify the problem.

Please guys, compare your project with the example project.

If the problem persists, at least send a link to a minimal reproduction case.

**Closed by douglasjunior** 2020-03-28 17:45 UTC
Labels: help wanted
