### ISSUE TITLE
 Authorization denied in IOS ,Location services is turned off but showing popup for fraction of second and dissappeared

### ISSUE THREAD

**Issue by raghvendra007** [douglasjunior/react-native-get-location#18] opened 2021-03-08 09:27 UTC
Authorization denied in IOS ,Location services is turned off from settings,  showing popup to turn on location for fraction of second and then pop dissappeared

**Comment by douglasjunior** [comment] 2021-03-08 11:14
Is it possible to reproduce with the [sample project](https://github.com/douglasjunior/react-native-get-location/tree/master/Sample)?

The library does not request a Dialog to enable GPS, [only requestWhenInUseAuthorization](https://github.com/douglasjunior/react-native-get-location/blob/master/ios/ReactNativeGetLocationLibrary/LocationModule.m#L59).

**Comment by raghvendra007** [comment] 2021-03-08 12:36
try {
        if (fetchLocationRequired) {
          places = await GetLocation.getCurrentPosition({
            enableHighAccuracy: true,
            timeout: 15000
          });
        }
      } catch (error) { 
        console.log("error>>>", error.message);
      }
since i have off location services in IOS ,it is giving message  Authorization denied and show popup for fraction of second in iphone x

**Comment by tadasstra** [comment] 2021-03-15 20:47
Same issue on my end. Made a temporary fix by not asking for location is location services are disabled. Edited LocationModule.m adding a check for locationServices:

```
      if ([CLLocationManager locationServicesEnabled]) {

          CLLocationManager *locationManager = [[CLLocationManager alloc] init];
          locationManager.delegate = self;
          locationManager.distanceFilter = kCLDistanceFilterNone;
          locationManager.desiredAccuracy = enableHighAccuracy ? kCLLocationAccuracyBest : kCLLocationAccuracyNearestTenMeters;

          mResolve = resolve;
          mReject = reject;
          mLocationManager = locationManager;
          mTimeout = timeout;

          if ([self isAuthorized]) {
            [self startUpdatingLocation];
          } else {
            [locationManager requestWhenInUseAuthorization];
          }

      } else {
          reject(@"CANCELLED", @"Location services not enabled", nil);
      }
```

**Comment by douglasjunior** [comment] 2021-03-16 11:32
Hi guys, I thank you for trying to help, but if you don't give me the information I need to find the problem, our conversation will never end. 

@tadasstra  by default, there is no need to check if the location is active inside Objective-C, because if is disabled, an exception will be thrown and in JavaScript you will receive an error with `UNAVAILABLE` code, like @raghvendra007 says.

Please guys, take a look at [usage example](https://github.com/douglasjunior/react-native-get-location#usage) and also [error codes](https://github.com/douglasjunior/react-native-get-location#error-codes).

**Comment by tadasstra** [comment] 2021-03-16 11:44
@douglasjunior yes you are right exception will be thrown, but together with exception the Native Dialog will be shown for a second and disappear. If the dialog is stays open then Settings button is not active and does not do anything. That's why the temp hack is to check is location is enabled to avoid the dialog. The dialog shown only when location is off on iPhone. To reproduce the dialog:

1. Switch off the location on iphone
2. Open app and call getCurrentPosition. Exception will catched.
3. Native dialog will be shown on top of the app (appstate will change to inactive) or it will show for a second and disappear.

![image](https://user-images.githubusercontent.com/24314113/111303507-4903d300-865d-11eb-8835-f6dc48103da5.png)

**Comment by douglasjunior** [comment] 2021-03-16 12:31
> @douglasjunior yes you are right exception will be thrown, but together with exception the Native Dialog will be shown for a second and disappear.

This is an unknown behavior for us, we have used the library in several projects here, and we have not yet encountered this situation.

So, without more information, or without an example to reproduce the problem, I will not be able to help you.

**Comment by tadasstra** [comment] 2021-03-16 13:01
Sure! Here are the steps:

**How did you link to the library (autolinking, manual, rn link, cocoapods)?**

Cocoapods

**What version of React Native?**

0.61.5

**What version of the library?**

2.0.0

**iOS/Android version?**

iOS 14.4

**Did the problem happen after updating React Native?**

No, fresh install

**Are you using the library for the first time?**

No

**It's a bug? Provide a link to a minimal reproduction case.**

Use Sample from your repo

1. Disable location on iphone. Make sure you didn't accept/deny location permissions before and it is first time.
2. Open Sample
3. Click Get Location
4. Turn on Location services dialog appears and disappears in a second. Authorization denied dialog shows after it.

**Comment by douglasjunior** [comment] 2021-03-26 13:08
Perfect, we managed to reproduce the problem, thanks!

**Comment by douglasjunior** [comment] 2021-03-26 13:52
Fixed in https://github.com/douglasjunior/react-native-get-location/releases/tag/2.1.0

**Closed by douglasjunior** 2021-03-26 13:52 UTC
Labels: bug
