### ISSUE TITLE
Getting Wrong location 

### ISSUE THREAD

**Issue by Aftab-web-dev** [douglasjunior/react-native-get-location#49] opened 2024-06-24 13:25 UTC
![image](https://github.com/douglasjunior/react-native-get-location/assets/84889160/600853f7-ad19-47c1-9fdf-0d8a2ba5f4ac)

**Comment by douglasjunior** [comment] 2024-06-24 13:51
Duplicate of #38, #37, #26, #17

**Closed by douglasjunior** 2024-06-24 13:51 UTC
